new & better ./configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6,6 +6,18 @@
 # licence:		GNU GPL
 #
 
+for tfile in "lncmd.py" "lnio.py" "lnlib.py" "main.py" "make/2Makefile" "make/test_getpass.py" "make/test_psycopg2.py" "make/test_sqlite3.py" "make/setupdb.py" "make/test_nntplib.py" "make/test_readline.py" "make/test_sys.py"
+do
+	echo "Checking for $tfile"
+	if test -e ./$tfile ; then
+		echo "OK! $tfile exist"
+	else
+		echo "Cannot find $tfile"
+		exit 1
+	fi
+done
+
+echo "Checking for python"
 if hash python 2>/dev/null; then
 	echo "Python installed"
 else
@@ -15,6 +27,7 @@ fi
 
 for mod in "getpass" "nntplib" "psycopg2" "readline" "sqlite3" "sys"
 do
+	echo "Checking for python-$mod"
 	lntest=`python make/test_$mod.py 2>/dev/null`
 	if test $lntest = "ok" ; then
 		echo "python-$mod installed"
@@ -23,6 +36,9 @@ do
 		exit 1
 	fi
 done
+
+echo 'Generating Makefile...'
+cp ./make/2Makefile ./Makefile
 
 echo 'Ready to install. Run `make install` to install lightnews'
 
